# Generated by Django 6.0.1 on 2026-01-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=112)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('Drama', 'Drama'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('Action', 'Action'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('romance', 'Romance')], default='Drama', max_length=55)),
                ('has_720p', models.BooleanField(default=False)),
                ('has_1080p', models.BooleanField(default=False)),
            ],
        ),
    ]
